### ISSUE TITLE
GPG-key list is only available on Git Bash

### ISSUE THREAD

**Issue by omarabdelaz1z** [KL13NT/initrepo#1]
### How to reproduce the problem

- Open windows CMD and `initrepo`.
- Type your local repo name.
- GPG key list is not shown.
![image](https://user-images.githubusercontent.com/59033999/180832172-98de46da-8c80-448c-9b6b-18a783f834e0.png)

**Comment by KL13NT** [comment]
I can repro this on my end. As a workaround, use initrepo in git bash as you usually do until a fix is released.

**Comment by KL13NT** [comment]
I could also add an error message for dependencies such as gpg. If its command fails, display possible causes.

**Comment by KL13NT** [comment]
Fixed in 7d7ae2a
